poorlynamedvariable={'VA1': ('Flank left!', ' https://gamepedia.cursecdn.com/paladins_gamepedia/f/f5/Evie_VGS_Attack_1.ogg'),
'VA2': ('Attack up the middle!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/c7/Evie_VGS_Attack_2.ogg'),
'VA3': ('Flank right!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f6/Evie_VGS_Attack_3.ogg'),
'VAA': ('attac', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/3a/Evie_VGS_Attack_A.ogg'),
'VAE': ('Attack the Siege Engine!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/9/94/Evie_VGS_Attack_E.ogg'),
'VAG': ('Attack the Objective!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/c1/Evie_VGS_Attack_G.ogg'),
'VB1': ('Enemies on the left flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/6/67/Evie_VGS_Enemy_1.ogg'),
'VB2': ('Enemies up the middle!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/57/Evie_VGS_Enemy_2.ogg'),
'VB3': ('Enemies on the right flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/d/d2/Evie_VGS_Enemy_3.ogg'),
'VBB': ('Enemies have returned to base!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/1/18/Evie_VGS_Enemy_B.ogg'),
'VBE': ('Enemies behind us!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/be/Evie_VGS_Enemy_E.ogg'),
'VBG': ('Enemies on the point!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/cc/Evie_VGS_Enemy_G.ogg'),
'VBI': ('Enemies incoming!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/73/Evie_VGS_Incoming_I.ogg'),
'VBS': ('Enemy spotted!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/4c/Evie_VGS_Enemy_S.ogg'),
'VC1': ('Be careful left flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/3b/Evie_VGS_Careful_1.ogg'),
'VC2': ('Be careful middle!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/48/Evie_VGS_Careful_2.ogg'),
'VC3': ('Be careful right flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/c8/Evie_VGS_Careful_3.ogg'),
'VCB': ('Return to base!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/54/Evie_VGS_Careful_B.ogg'),
'VCC': ('Be careful!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/6/6a/Evie_VGS_Careful_C.ogg'),
'VD1': ('Defend left flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/fe/Evie_VGS_Defend_1.ogg'),
'VD2': ('Defend the middle!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/2/2b/Evie_VGS_Defend_2.ogg'),
'VD3': ('Defend right flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/32/Evie_VGS_Defend_3.ogg'),
'VDD': ('Defend!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/84/Evie_VGS_Defend_D.ogg'),
'VDE': ('Defend the Sieg Engine!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/8d/Evie_VGS_Defend_E.ogg'),
'VDG': ('Defend the objective!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/9/9c/Evie_VGS_Defend_G.ogg'),
'VEA': ('Awesomesauce!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/54/Evie_VGS_Emote_A_Alt4.ogg'),
'VEG': ('\\*air succ\\* MEEEEEEEEEEEEEEEEEEEEEEEE!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/2/22/Evie_VGS_Emote_G_Alt1.ogg'),
'VER': ("You're the puma's pyjamas!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/44/Evie_VGS_Emote_R_Alt.ogg'),
'VEW': ('WOOOOOOO! Wahoooo!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/7c/Evie_VGS_Emote_W_Alt2.ogg'),
'VH1': ('Help left flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f2/Evie_VGS_Help_1.ogg'),
'VH2': ('Help the middle!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/7e/Evie_VGS_Help_2.ogg'),
'VH3': ('Help right flank!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/70/Evie_VGS_Help_3.ogg'),
'VHH': ('I am a totally incompetent player who requires the assistance of teammates as a crutch! (Alternatively, if I am a support, "***PEEL FOR ME***")', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/b6/Evie_VGS_Help.ogg'),
'VHS': ('*I   N E E D   H E A L I N G*', 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/84/Evie_VGS_Help_S.ogg'),
'VRR': ("i swear to jenos if you feed them ult charge i'll call you a heck", 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/41/Evie_VGS_Retreat_R.ogg'),
'VRS': ("You don't actually need healing!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/1/14/Evie_VGS_Retreat_S.ogg'),
'VSO': ("I'm on it!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f8/Evie_VGS_Self_O.ogg'),
'VSR': ('Falling back!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/36/Evie_VGS_Self_R.ogg'),
'VSA1': ("I'll attack left flank!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/c9/Evie_VGS_Self_Attack_1_Alt.ogg'),
'VSA2': ("I'll attach up the middle!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/30/Evie_VGS_Self_Attack_2.ogg'),
'VSA3': ("I'll attack right flank!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f0/Evie_VGS_Self_Attack_3.ogg'),
'VSAA': ('she attac', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f8/Evie_VGS_Self_Attack.ogg'),
'VSAB': ("I'll overextend and spawnca- err I mean zone them! Don't worry, I can just soar back!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/a/a6/Evie_VGS_Self_Attack_B.ogg'),
'VSAG': ('jenos not capping point smh', 'https://gamepedia.cursecdn.com/paladins_gamepedia/1/1f/Evie_VGS_Self_Attack_G.ogg'),
'VSD1': ("I'll defend left flank!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/86/Evie_VGS_Self_Defend_1.ogg'),
'VSD2': ("I'll defend the middle!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/a/a1/Evie_VGS_Self_Defend_2.ogg'),
'VSD3': ("I'll defend right flank", 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/7a/Evie_VGS_Self_Defend_3.ogg'),
'VSDB': ("I'll AFK in spawn!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/6/6d/Evie_VGS_Self_Defend_B.ogg'),
'VSDD': ("I'll defend!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/80/Evie_VGS_Self_Defend.ogg'),
'VSDG': ("I'll defend the objective!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/a/a1/Evie_VGS_Self_Defend_G.ogg'),
'VVA': ('Okay!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/d/d6/Evie_VGS_OK.ogg'),
'VVB': ('Be right back!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/f3/Evie_VGS_BRB.ogg'),
'VVC': ('Completed!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/0/08/Evie_VGS_Completed.ogg'),
'VVK': ('Stepping away for a moment!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/4c/Evie_VGS_AFK.ogg'),
'VVN': ('No!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/4e/Evie_VGS_Emote_No.ogg'),
'VVP': ('Pleeease?', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/fd/Evie_VGS_Emote_Please.ogg'),
'VVS': ('Sorry.', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/5f/Evie_VGS_Other_S_Alt.ogg'),
'VVT': ('Thanks!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/5e/Evie_VGS_Thanks.ogg'),
'VVW': ('Wait!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/86/Evie_VGS_Other_W.ogg'),
'VVX': ('oh look another dredge top play', 'https://gamepedia.cursecdn.com/paladins_gamepedia/5/51/Evie_VGS_Cancel.ogg'),
'VVY': ('Yes!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/0/08/Evie_VGS_Emote_Yes.ogg'),
'VVGB': ('Bye bye now!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/f/fa/Evie_VGS_Other_G_B.ogg'),
'VVGF': ('Go play!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/b1/Evie_VGS_Emote_F_Alt.ogg'),
'VVGG': ('GG!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/e/ee/Evie_VGS_Other_G_G.ogg'),
'VVGH': ('Hiiii!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/85/Evie_VGS_Other_G_H.ogg'),
'VVGL': ('Best of luck!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/be/Evie_VGS_Other_G_L.ogg'),
'VVGN': ('Ooooh, nice one!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/e/e9/Evie_VGS_NiceJob.ogg'),
'VVGO': ('Oopsie daisy!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/ce/Evie_VGS_Other_G_O.ogg'),
'VVGQ': ('Shut your c*kehole!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/cd/Evie_VGS_Other_G_Q.ogg'),
'VVGR': ('No problem!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/e/e2/Evie_VGS_Other_G_R.ogg'),
'VVGS': ('Darnit!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/9/9d/Evie_VGS_Other_G_S.ogg'),
'VVGT': ('That stinks.', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/be/Evie_VGS_Other_G_T.ogg'),
'VVGW': ("You're welcome!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/43/Evie_VGS_Other_G_W.ogg'),
'VVVA': ("Quick, hide in skye's (malfunctioning) smoke bomb!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/41/Evie_VGS_Other_V_A_Alt.ogg'),
'VVVB': ('Oh, from behind?', 'https://gamepedia.cursecdn.com/paladins_gamepedia/0/05/Evie_VGS_Other_V_B.ogg'),
'VVVC': ('Chase the enemy!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/33/Evie_VGS_Other_V_C.ogg'),
'VVVD': ('Ultimate is down!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/2/28/Evie_VGS_Other_V_D.ogg'),
'VVVE': ('On my way!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/4/4e/Evie_VGS_Other_V_W.ogg'),
'VVVF': ('Have fun! ^^^^^^^^^^^^^haha, ^^^^^^^^^^^^^right. ^^^^^^^^^^^^^*fun.*', 'https://gamepedia.cursecdn.com/paladins_gamepedia/b/b2/Evie_VGS_Other_V_F.ogg'),
'VVVG': ('Group up!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/70/Evie_VGS_Other_V_G.ogg'),
'VVVR': ('Ultimate is ready!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/7/71/Evie_VGS_Other_V_R.ogg'),
'VVVS': ('Stay here!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/1/11/Evie_VGS_Other_V_S.ogg'),
'VVVT': ("It's a trap!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/d/da/Evie_VGS_Other_V_T.ogg'),
'VVVX': ('Spread out!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/d/dd/Evie_VGS_Other_V_X.ogg'),
'VVVM': ('Out of Mana!', 'https://gamepedia.cursecdn.com/paladins_gamepedia/3/30/Evie_VGS_Other_G_M.ogg'),
'VEL': ('Haahahahahahahaha!', 'https://d1u5p3l4wpay3k.cloudfront.net/paladins_gamepedia/0/0e/Evie_SP_Laugh_4.ogg'),
'VEJ': ("-Knock knock! -Who's there? –Icy! -Icy who? –Icy your gates are burning! HAHAHaHAHAHAa!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/c/c4/Evie_SP_Joke_2_a.ogg'),
'VET': ("That's it, keep talkin', pally - you 'bout to get messed up!", 'https://gamepedia.cursecdn.com/paladins_gamepedia/8/8c/Evie_SP_Taunt_3_a.ogg'),
'VSAE': ('hi rez add this voiceline pls', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ')
}